### ISSUE TITLE
Unable to locate package php7.4-swoole

### ISSUE THREAD

**Issue by darshithedpara** [the-dijkstra/tryphp#1]
First of all, this is so cool 🎉
I believe Laravel should use something like this instead of `https://php.new` which provides only php8.3

I was installing php7.4 but it ended with errors.

![image](https://github.com/user-attachments/assets/f71b9ac8-9874-4cc9-9da1-f3c06fa1a217)

**Comment by mhdcodes** [comment]
hey thanks @darshithedpara for using this tool! currently, all php presets only install default extensions; no framework-specific extensions are included to keep it minimal. we’ll add a laravel-specific preset in the future to install everything needed for laravel.

in the meanwhile you can try to install your extension manualy:

```shell
sudo apt install php7.4-swoole
```

**Comment by mhdcodes** [comment]
Laravel preset has been added:

```shell
curl -fsSL https://tryphp.dev/presets/laravel | bash
```

**Comment by darshithedpara** [comment]
Wow so fast :fire:  

```sh
curl -fsSL https://tryphp.dev/7.4/install.sh | bash
```

but this is broken FYI.

**Comment by mhdcodes** [comment]
> Wow so fast 🔥
> 
> ```shell
> curl -fsSL https://tryphp.dev/7.4/install.sh | bash
> ```
> 
> but this is broken FYI.

would you illustrate more ?

**Comment by darshithedpara** [comment]
I tried in fresh installation.

OS : Ubuntu noble 24.04 x86_64
Kernel : Linux 6.8.0-48-generic

```sh
curl -fsSL https://tryphp.dev/7.4/install.sh | bash
```
The command ends with the below output.

> INFO  Installing PHP and extensions...
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package php7.4-swoole
> E: Couldn't find any package by glob 'php7.4-swoole'
> E: Couldn't find any package by regex 'php7.4-swoole'

**Comment by mhdcodes** [comment]
hmm indeed the PHP presets include `php7.4-swoole` by default I will remove it and keep it minimal.
